services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://backend:8000
    volumes:
      - hydraulic_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /app/backend
    command: python run.py
    ports:
      - "8000:8000"
    environment:
      - PORT=8000

volumes:
  hydraulic_data:
